# resolver: lts-18.28
resolver: lts-19.33

packages:
  - .

extra-deps:
- ihaskell-blaze-0.3.0.1
#- liquidhaskell-0.8.10.7
#- liquid-fixpoint-0.8.10.7
- liquid-ghc-prim-0.7.0@sha256:8d99d771235d388ed54393faa2712c880e60b659fa574877fc5f383d4d49f4ed,1763
- liquid-prelude-0.8.10.2@sha256:b2a3650092e3eecfff5e5b15052700c2d6ba5eecbf20d91eae552da23783b03e,1604
- rest-rewrite-0.3.0
- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: b86fb5b461a70d07fb7e97ccdbdd0ee330bf3396 # 900c583d78ecdffd937609453861c3f2e8ed7a23
  subdirs:
    - .
    - liquid-fixpoint
- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 16033ac4b90e11ad4fb2f6b866b905ff765dbac7
  subdirs:
    - liquid-base
    - liquid-containers

nix:
  shell-file: ./shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

allow-newer: true
